version: '3.4'
services:
  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - wordpressv2_network


networks:
  wordpressv2_network:
    external: true