CREATE TABLE PERSONA (
  ID    BIGINT auto_increment PRIMARY KEY,
  NOMBRE  VARCHAR(100) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL);


INSERT INTO PERSONA (NOMBRE, FECHA_NACIMIENTO) VALUES ('Pedro García', '2010-01-01')